version: '3'

services:
  # Service PHP avec Apache
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:80"
    depends_on:
      - db
    restart: always
  
  # Service MySQL
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monsite
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "1100:3306"
    restart: always
  
  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "6969:80"
    depends_on:
      - db
    restart: always

# Volume pour les données MySQL
volumes:
  db_data: